# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R2Cx4rzGVhv92nH6my7Tbr9dNS1rB-BO
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score

df = pd.read_csv("/content/Car data.csv")
print(df.head())

df['Onroad Price'] = df['Onroad Price'].str.replace(',', '')
df['Onroad Price'] = df['Onroad Price'].astype(float)

df['Type'] = df['Type'].str.strip()

df.drop('Name', axis=1, inplace=True)

df.fillna(method='ffill', inplace=True)

le_type = LabelEncoder()
df['Type'] = le_type.fit_transform(df['Type'])

X = df.drop('Onroad Price', axis=1)
y = df['Onroad Price']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)

xgb_model = XGBRegressor(n_estimators=100, learning_rate=0.1)
xgb_model.fit(X_train, y_train)

xgb_pred = xgb_model.predict(X_test)

rf_rmse = np.sqrt(mean_squared_error(y_test, rf_pred))
xgb_rmse = np.sqrt(mean_squared_error(y_test, xgb_pred))

print("Random Forest RMSE:", rf_rmse)
print("XGBoost RMSE:", xgb_rmse)

import pickle

pickle.dump(rf_model, open("rf_model.pkl", "wb"))
pickle.dump(xgb_model, open("xgb_model.pkl", "wb"))
pickle.dump(scaler, open("scaler.pkl", "wb"))

ensemble_pred = (rf_pred + xgb_pred) / 2

ensemble_rmse = np.sqrt(mean_squared_error(y_test, ensemble_pred))
print("Ensemble RMSE:", ensemble_rmse)

def recommend_car():
    print("\nEnter your preferences:")

    min_price = float(input("Min Price (Lakh): "))
    max_price = float(input("Max Price (Lakh): "))
    mileage = float(input("Mileage (kmpl): "))
    cc = int(input("Engine CC: "))
    seats = int(input("Seats: "))
    variants = int(input("Variants: "))
    fuel = input("Fuel Type (Petrol/Diesel): ")

    fuel = le_type.transform([fuel.strip()])[0]

    user_data = np.array([[min_price, max_price, mileage, cc, seats, variants,
                           fuel, 0, 0, 0, 0]])

    user_scaled = scaler.transform(user_data)

    rf_out = rf_model.predict(user_scaled)
    xgb_out = xgb_model.predict(user_scaled)

    final_price = (rf_out + xgb_out) / 2

    print("\nEstimated On-Road Price:", int(final_price[0]))

recommend_car()

from flask import Flask, request, jsonify
import numpy as np
import pickle

app = Flask(__name__)

# Load models
rf_model = pickle.load(open("rf_model.pkl", "rb"))
xgb_model = pickle.load(open("xgb_model.pkl", "rb"))
scaler = pickle.load(open("scaler.pkl", "rb"))

@app.route('/')
def home():
    return "Car Recommendation API Running"

@app.route('/predict', methods=['POST'])
def predict():
    data = request.json

    features = np.array(data['features']).reshape(1, -1)
    features_scaled = scaler.transform(features)

    rf_pred = rf_model.predict(features_scaled)
    xgb_pred = xgb_model.predict(features_scaled)

    result = (rf_pred + xgb_pred) / 2

    return jsonify({
        "Predicted Onroad Price": float(result[0])
    })

if __name__ == "__main__":
    app.run()